spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/customer_management
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

logging:
  level:
    com.lciii.tup.customer_management_service: INFO
    org.springframework.web: WARN
    org.hibernate.SQL: WARN 